FROM rust:latest AS build
WORKDIR /build
COPY . .
RUN apt update && apt install cmake unzip curl -y && cargo build --release

FROM rust:slim-bookworm
WORKDIR /app
COPY --from=build /build/.env /build/target/release/rmq-aws /app/
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
RUN unzip awscliv2.zip 
RUN ./aws/install
CMD ["sh", "-c", "./rmq-aws"]