FROM node AS build

WORKDIR /build
COPY . .
RUN npm i && npm run build

FROM node:alpine

WORKDIR /app
COPY package.json package-lock.json .env ./
RUN npm ci --production
COPY --from=build /build/dist ./

CMD ["node", "src/main.js"]